# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptocurrencyExchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptocurrencyExchange

  # SpreadSheet
  pod 'SpreadsheetView'
  pod 'Alamofire'
  pod 'Starscream', '~> 4.0.0'
  pod 'Charts'
  pod 'RealmSwift'
 
  target 'CryptocurrencyExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptocurrencyExchangeUITests' do
    # Pods for testing
  end

end
